// <auto-generated />
using System;
using AddiScan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddiScan.Infrastructure.Migrations
{
    [DbContext(typeof(AddiScanDbContext))]
    partial class AddiScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AddiScan.Core.Entities.Additive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannedAnywhere")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("CommonNamesAndSynonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ENumber")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EvidenceSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoundIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HealthConcerns")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastResearched")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameVerbatim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegulatoryNoteFromSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("SideEffects")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceOrigin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Additives");
                });

            modelBuilder.Entity("AddiScan.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConsentGivenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AddiScan.Core.Entities.Additive", b =>
                {
                    b.OwnsOne("AddiScan.Core.Entities.SafetyGrading", "Grading", b1 =>
                        {
                            b1.Property<int>("AdditiveId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AllergicReactionsNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("AllergicReactionsScore")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("BanStatusNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("BanStatusScore")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CarcinogenicityNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CarcinogenicityScore")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ChildrenAndVulnerableNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("ChildrenAndVulnerableScore")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CumulativeRiskNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("CumulativeRiskScore")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal?>("FinalScore")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FunctionalNecessityNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("FunctionalNecessityScore")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Graded")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OriginNote")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("OriginScore")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RawPoints")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("RiskBand")
                                .HasColumnType("INTEGER");

                            b1.HasKey("AdditiveId");

                            b1.ToTable("Additives");

                            b1.WithOwner()
                                .HasForeignKey("AdditiveId");
                        });

                    b.Navigation("Grading");
                });
#pragma warning restore 612, 618
        }
    }
}
